<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>C&#43;&#43;程序闪退原因定位 - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="C&#43;&#43;程序闪退原因定位" />
<meta property="og:description" content="内部直接或者间接调用了terminate函数或者abort函数，terminate函数内部也是默认调用了abort函数。 C&#43;&#43;异常处理之terminate函数 C&#43;&#43;中处理异常的过程是这样的：在执行程序发生异常，可以不在本函数中处理，而是抛出一个错误信息，把它传递给上一级的函数来解决，上一级解决不了，再传给其上一级，由其上一级处理。如此逐级上传，直到最高一级还无法处理的话，运行系统会自动调用系统函数terminate，
学会使用terminate函数有助于异常处理
一 当一个异常产生的时候调用terminate函数，代码：
[cpp] view plaincopyprint?
#include &lt;iostream&gt; #include &lt;exception&gt; using namespace std; void on_terminate(){ cout&lt;&lt;&#34;terninate function called!&#34;&lt;&lt;endl; cin.get(); } int main(void){ set_terminate(on_terminate); throw exception(); cout&lt;&lt;&#34;terminate function not called!&#34;&lt;&lt;endl; cin.get(); return 0; } terminate被调用的情况：
1 当发送一个异常，并且构造函数产生异常
2 当发送一个异常，或者析构函数产生异常
3 一个静态对象的构造或者析构发送一个异常
4 以atexit注册的函数发生异常的时候
5 自定义一个异常，但是实际上没有异常产生的时候
6 调用缺省的unexcepted()函数时候
例子说话：
[cpp] view plaincopyprint?
#include &lt;iostream&gt; #include &lt;exception&gt; using namespace std; void on_terminate(){ cout&lt;&lt;&#34;terminate function called!&#34;&lt;&lt;endl; cin.get(); } class custom_exception{ custom_exception(){ } custom_exception(const custom_exception&amp; excep){ throw exception(); } }; void case_1(){ try{ throw custom_exception(); } catch(." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/48d35f1865a7e8eb902b50bd93dec89c/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2022-03-29T11:00:27+08:00" />
<meta property="article:modified_time" content="2022-03-29T11:00:27+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">C&#43;&#43;程序闪退原因定位</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <ol><li style="text-align:justify;">内部直接或者间接调用了terminate函数或者abort函数，terminate函数内部也是默认调用了abort函数。</li></ol> 
<h2 style="margin-left:0pt;text-align:left;"><strong><strong><span style="background-color:#ffffff;"><span style="color:#222226;"><strong>C++异常处理之terminate函数</strong></span></span></strong></strong></h2> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">C++中处理异常的过程是这样的：在执行程序发生异常，可以不在本函数中处理，而是抛出一个错误信息，把它传递给上一级的函数来解决，上一级解决不了，再传给其上一级，由其上一级处理。如此逐级上传，直到最高一级还无法处理的话，运行系统会自动调用系统函数terminate，</span></p> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">学会使用terminate函数有助于异常处理</span></p> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">一 当一个异常产生的时候调用terminate函数，代码：</span></p> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">[cpp] view plaincopyprint?</span></p> 
<ol><li style="text-align:justify;">#include &lt;iostream&gt;   </li><li style="text-align:justify;">#include &lt;exception&gt;   </li><li style="text-align:justify;">using namespace std;  </li><li style="text-align:justify;">void on_terminate(){  </li><li style="text-align:justify;"> cout&lt;&lt;"terninate function called!"&lt;&lt;endl;  </li><li style="text-align:justify;"> cin.get();  </li><li style="text-align:justify;">}  </li><li style="text-align:justify;">int main(void){  </li><li style="text-align:justify;"> set_terminate(on_terminate);  </li><li style="text-align:justify;"> throw exception();  </li><li style="text-align:justify;"> cout&lt;&lt;"terminate function not called!"&lt;&lt;endl;  </li><li style="text-align:justify;"> cin.get();  </li><li style="text-align:justify;"> return 0;  </li><li style="text-align:justify;">}  </li></ol> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">terminate被调用的情况：</span><br><span style="color:#4d4d4d;">1 当发送一个异常，并且构造函数产生异常</span><br><span style="color:#4d4d4d;">2 当发送一个异常，或者析构函数产生异常</span><br><span style="color:#4d4d4d;">3 一个静态对象的构造或者析构发送一个异常</span><br><span style="color:#4d4d4d;">4 以atexit注册的函数发生异常的时候</span><br><span style="color:#4d4d4d;">5 自定义一个异常，但是实际上没有异常产生的时候</span><br><span style="color:#4d4d4d;">6 调用缺省的unexcepted()函数时候</span><br><span style="color:#4d4d4d;">例子说话：</span><br>  </p> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">[cpp] view plaincopyprint?</span></p> 
<ol><li style="text-align:justify;">#include &lt;iostream&gt;   </li><li style="text-align:justify;">#include &lt;exception&gt;   </li><li style="text-align:justify;">using namespace std;  </li><li style="text-align:justify;">void on_terminate(){  </li><li style="text-align:justify;"> cout&lt;&lt;"terminate function called!"&lt;&lt;endl;  </li><li style="text-align:justify;"> cin.get();  </li><li style="text-align:justify;">}  </li><li style="text-align:justify;">class custom_exception{  </li><li style="text-align:justify;"> custom_exception(){  </li><li style="text-align:justify;"> }  </li><li style="text-align:justify;"> custom_exception(const custom_exception&amp; excep){  </li><li style="text-align:justify;">  throw exception();  </li><li style="text-align:justify;"> }  </li><li style="text-align:justify;">};  </li><li style="text-align:justify;">void case_1(){  </li><li style="text-align:justify;"> try{  </li><li style="text-align:justify;">  throw custom_exception();  </li><li style="text-align:justify;"> }  </li><li style="text-align:justify;"> catch(...){  </li><li style="text-align:justify;"> }  </li><li style="text-align:justify;">}  </li></ol> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">当一个函数抛出了一个throw异常的时候，如果该函数内部构造了对象的话，系统会先对该对象调用析构函数，当对象调用完了析构函数以后，才开始执行异常的抛出工作。</span><br><span style="color:#4d4d4d;">同时在具有继承关系的类的异常中，子类的异常应该放在前面，而基类的异常应该放到最后面，这样可以使子类的异常先获得处理，父类的异常最后处理。</span><br>  </p> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">[cpp] view plaincopyprint?</span></p> 
<ol><li style="text-align:justify;">#include&lt;iostream&gt;    </li><li style="text-align:justify;">using namespace std;   </li><li style="text-align:justify;">class X   </li><li style="text-align:justify;">{   </li><li style="text-align:justify;">public:   </li><li style="text-align:justify;"> class Trouble {};   //注意：类中嵌套类的申明和定义，学习!!!    </li><li style="text-align:justify;">  class small: public Trouble {};   </li><li style="text-align:justify;">  class big:public Trouble {};//类中的继承!!!    </li><li style="text-align:justify;">  void f(){   </li><li style="text-align:justify;">  throw big();   </li><li style="text-align:justify;"> }   </li><li style="text-align:justify;">};   </li><li style="text-align:justify;">int main()   </li><li style="text-align:justify;">{   </li><li style="text-align:justify;">  X x;   </li><li style="text-align:justify;">  try{   </li><li style="text-align:justify;">    x.f();   </li><li style="text-align:justify;">  }   </li><li style="text-align:justify;">  catch(X::Trouble &amp;)   </li><li style="text-align:justify;">  {   </li><li style="text-align:justify;">    cout&lt;&lt;"caught Trouble"&lt;&lt;endl;   </li><li style="text-align:justify;">  }   </li><li style="text-align:justify;">  catch(X::small&amp;)   </li><li style="text-align:justify;">  {   </li><li style="text-align:justify;">    cout&lt;&lt;"caught small"&lt;&lt;endl;  </li><li style="text-align:justify;"> }   </li><li style="text-align:justify;">  catch(X::big&amp;)   </li><li style="text-align:justify;">  {   </li><li style="text-align:justify;">    cout&lt;&lt;"caught big"&lt;&lt;endl;   </li><li style="text-align:justify;">  }   </li><li style="text-align:justify;">   return 0;   </li><li style="text-align:justify;">}   </li></ol> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">如果这样的话，抛出的big()类型异常则被trouble类垄断，应该倒着写才可以实现顺序捕获所有异常，另外使用...可以捕捉所有的异常，这个应该放到最后面才可以。</span><br><span style="color:#4d4d4d;">省略号异常处理器不允许接受任何参数，所以无法得到任何相关异常的信息，也无法知道异常的类型，这种catch语句经常用于清理资源并重新抛出所捕获的异常。</span></p> 
<p style="margin-left:0;text-align:left;"><span style="color:#4d4d4d;">Terminate或者abort结束的程序 ， 会在windows事件查看器上面反映出来</span></p> 
<p style="margin-left:0;text-align:left;"><img alt="" height="318" src="https://images2.imgbox.com/9d/19/KfbxNpZQ_o.png" width="554"></p> 
<p> </p> 
<p style="margin-left:.0001pt;text-align:justify;"></p> 
<p style="margin-left:.0001pt;text-align:justify;"></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/8372ee6ee40fb7b71e9484527117de27/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Java算法学习13——最近公共祖先</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/2320805baf24caef013b52d497f9e01c/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">【教你搭建服务器系列】（2）搭建服务器环境，安装JDK、MySQL、Redis、Tomcat、Nginx</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>