<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>详解C&#43;&#43;异常处理方式 - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="详解C&#43;&#43;异常处理方式" />
<meta property="og:description" content="目录
1.C语言传统的处理错误的方式
2. C&#43;&#43;异常概念
3. 异常的使用
3.1 异常的抛出和捕获
3.2 异常的重新抛出
3.3异常安全 3.4 异常规范
4.自定义异常体系
5.C&#43;&#43;标准库的异常体系 6.异常的优缺点
1.C语言传统的处理错误的方式 传统的错误处理机制：
1. 终止程序，如assert，缺陷：用户难以接受。如发生内存错误，除0错误时就会终止程序。
2. 返回错误码，缺陷：需要程序员自己去查找对应的错误。如系统的很多库的接口函数都是通
过把错误码放到errno中，表示错误
实际中C语言基本都是使用返回错误码的方式处理错误，部分情况下使用终止程序处理非常严重的
错误。
2. C&#43;&#43;异常概念 异常是一种处理错误的方式，当一个函数发现自己无法处理的错误时就可以抛出异常，让函数的
直接或间接的调用者处理这个错误。
throw: 当问题出现时，程序会抛出一个异常。这是通过使用 throw 关键字来完成的。
catch: 在您想要处理问题的地方，通过异常处理程序捕获异常.catch 关键字用于捕获异
常，可以有多个catch进行捕获。
try: try 块中的代码标识将被激活的特定异常,它后面通常跟着一个或多个 catch 块。
如果有一个块抛出一个异常，捕获异常的方法会使用 try 和 catch 关键字。try 块中放置可能抛
出异常的代码，try 块中的代码被称为保护代码。使用 try/catch 语句的语法如下所示：
try { // 保护的标识代码 } catch (ExceptionName e1) { // catch 块 } catch (ExceptionName e2) { // catch 块 } catch (ExceptionName eN) { // catch 块 } 3." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/82093a34fcf20332594f770e0fd57173/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-03-26T16:04:18+08:00" />
<meta property="article:modified_time" content="2023-03-26T16:04:18+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">详解C&#43;&#43;异常处理方式</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p id="main-toc"><strong>目录</strong></p> 
<p id="-toc" style="margin-left:0px;"></p> 
<p id="1.C%E8%AF%AD%E8%A8%80%E4%BC%A0%E7%BB%9F%E7%9A%84%E5%A4%84%E7%90%86%E9%94%99%E8%AF%AF%E7%9A%84%E6%96%B9%E5%BC%8F-toc" style="margin-left:0px;"><a href="#1.C%E8%AF%AD%E8%A8%80%E4%BC%A0%E7%BB%9F%E7%9A%84%E5%A4%84%E7%90%86%E9%94%99%E8%AF%AF%E7%9A%84%E6%96%B9%E5%BC%8F" rel="nofollow">1.C语言传统的处理错误的方式</a></p> 
<p id="2.%20C%2B%2B%E5%BC%82%E5%B8%B8%E6%A6%82%E5%BF%B5-toc" style="margin-left:0px;"><a href="#2.%20C%2B%2B%E5%BC%82%E5%B8%B8%E6%A6%82%E5%BF%B5" rel="nofollow">2. C++异常概念</a></p> 
<p id="3.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8-toc" style="margin-left:0px;"><a href="#3.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8" rel="nofollow">3. 异常的使用</a></p> 
<p id="3.1%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E6%8D%95%E8%8E%B7-toc" style="margin-left:40px;"><a href="#3.1%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E6%8D%95%E8%8E%B7" rel="nofollow">3.1 异常的抛出和捕获</a></p> 
<p id="3.2%20%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA-toc" style="margin-left:40px;"><a href="#3.2%20%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA" rel="nofollow">3.2 异常的重新抛出</a></p> 
<p id="3.3%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8%C2%A0-toc" style="margin-left:40px;"><a href="#3.3%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8%C2%A0" rel="nofollow">3.3异常安全 </a></p> 
<p id="3.4%20%E5%BC%82%E5%B8%B8%E8%A7%84%E8%8C%83-toc" style="margin-left:40px;"><a href="#3.4%20%E5%BC%82%E5%B8%B8%E8%A7%84%E8%8C%83" rel="nofollow">3.4 异常规范</a></p> 
<p id="4.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB-toc" style="margin-left:0px;"><a href="#4.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB" rel="nofollow">4.自定义异常体系</a></p> 
<p id="5.C%2B%2B%E6%A0%87%E5%87%86%E5%BA%93%E7%9A%84%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%C2%A0-toc" style="margin-left:0px;"><a href="#5.C%2B%2B%E6%A0%87%E5%87%86%E5%BA%93%E7%9A%84%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%C2%A0" rel="nofollow">5.C++标准库的异常体系 </a></p> 
<p id="6.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BC%98%E7%BC%BA%E7%82%B9-toc" style="margin-left:0px;"><a href="#6.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BC%98%E7%BC%BA%E7%82%B9" rel="nofollow">6.异常的优缺点</a></p> 
<hr id="hr-toc"> 
<p></p> 
<h2 id="1.C%E8%AF%AD%E8%A8%80%E4%BC%A0%E7%BB%9F%E7%9A%84%E5%A4%84%E7%90%86%E9%94%99%E8%AF%AF%E7%9A%84%E6%96%B9%E5%BC%8F"><span style="color:#0d0016;">1.C语言传统的处理错误的方式</span></h2> 
<p><span style="color:#0d0016;">传统的错误处理机制：<br> 1. 终止程序，如assert，缺陷：用户难以接受。如发生内存错误，除0错误时就会终止程序。<br> 2. 返回错误码，缺陷：需要程序员自己去查找对应的错误。如系统的很多库的接口函数都是通<br> 过把错误码放到errno中，表示错误<br> 实际中C语言基本都是使用返回错误码的方式处理错误，部分情况下使用终止程序处理非常严重的<br> 错误。</span></p> 
<p><img alt="" height="244" src="https://images2.imgbox.com/43/86/TPtsNEhB_o.png" width="851"></p> 
<h2 id="2.%20C%2B%2B%E5%BC%82%E5%B8%B8%E6%A6%82%E5%BF%B5"><span style="color:#0d0016;">2. C++异常概念</span></h2> 
<p><span style="color:#0d0016;">异常是一种处理错误的方式，当一个函数发现自己无法处理的错误时就可以抛出异常，让函数的<br> 直接或间接的调用者处理这个错误。<br>         throw: 当问题出现时，程序会抛出一个异常。这是通过使用 throw 关键字来完成的。<br>         catch: 在您想要处理问题的地方，通过异常处理程序捕获异常.catch 关键字用于捕获异<br>         常，可以有多个catch进行捕获。<br>         try: try 块中的代码标识将被激活的特定异常,它后面通常跟着一个或多个 catch 块。<br> 如果有一个块抛出一个异常，捕获异常的方法会使用 try 和 catch 关键字。try 块中放置可能抛<br> 出异常的代码，try 块中的代码被称为保护代码。使用 try/catch 语句的语法如下所示：</span></p> 
<pre><code class="language-cpp">try
{
	// 保护的标识代码
}
catch (ExceptionName e1)
{
	// catch 块
}
catch (ExceptionName e2)
{
	// catch 块
}
catch (ExceptionName eN)
{
	// catch 块
}</code></pre> 
<h2 id="3.%20%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%BF%E7%94%A8"><span style="color:#0d0016;">3. 异常的使用</span></h2> 
<h3 id="3.1%20%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E6%8D%95%E8%8E%B7"><span style="color:#0d0016;">3.1 异常的抛出和捕获</span></h3> 
<p><span style="color:#0d0016;"><strong>异常的抛出和匹配原则</strong><br> 1. 异常是通过抛出对象而引发的，该对象的类型决定了应该激活哪个catch的处理代码。<br> 2. 被选中的处理代码是调用链中与该对象类型匹配且离抛出异常位置最近的那一个。<br> 3. 抛出异常对象后，会生成一个异常对象的拷贝，因为抛出的异常对象可能是一个临时对象，<br> 所以会生成一个拷贝对象，这个拷贝的临时对象会在被catch以后销毁。（这里的处理类似<br> 于函数的传值返回）<br> 4. catch(...)可以捕获任意类型的异常，问题是不知道异常错误是什么。<br> 5. 实际中抛出和捕获的匹配原则有个例外，并不都是类型完全匹配，可以抛出的派生类对象，<br> 使用基类捕获，这个在实际中非常实用。</span></p> 
<p><span style="color:#0d0016;"><strong>在函数调用链中异常栈展开匹配原则</strong><br> 1. 首先检查throw本身是否在try块内部，如果是再查找匹配的catch语句。如果有匹配的，则<br> 调到catch的地方进行处理。<br> 2. 没有匹配的catch则退出当前函数栈，继续在调用函数的栈中进行查找匹配的catch。<br> 3. 如果到达main函数的栈，依旧没有匹配的，则终止程序。上述这个沿着调用链查找匹配的<br> catch子句的过程称为栈展开。所以实际中我们最后都要加一个catch(...)捕获任意类型的异<br> 常，否则当有异常没捕获，程序就会直接终止。<br> 4. 找到匹配的catch子句并处理以后，会继续沿着catch子句后面继续执行。</span></p> 
<p><img alt="" height="516" src="https://images2.imgbox.com/0a/92/i9V3PZxr_o.png" width="761"></p> 
<pre><code class="language-cpp">double Division(int a, int b)
{
	// 当b == 0时抛出异常
	if (b == 0)
		throw "Division by zero condition!";
	else
		return ((double)a / (double)b);
}
void Func()
{
	int len, time;
	cin &gt;&gt; len &gt;&gt; time;
	cout &lt;&lt; Division(len, time) &lt;&lt; endl;
}
int main()
{
	try 
	{
		Func();
	}
	catch (const char* errmsg)
	{
		cout &lt;&lt; errmsg &lt;&lt; endl;
	}
	catch (...) 
	{
			cout &lt;&lt; "unkown exception" &lt;&lt; endl;
	}
	return 0;
}</code></pre> 
<p><span style="color:#0d0016;">运行截图：</span></p> 
<p><img alt="" height="66" src="https://images2.imgbox.com/f0/26/4T7MTnMU_o.png" width="485"></p> 
<h3 id="3.2%20%E5%BC%82%E5%B8%B8%E7%9A%84%E9%87%8D%E6%96%B0%E6%8A%9B%E5%87%BA"><span style="color:#0d0016;">3.2 异常的重新抛出</span></h3> 
<p><span style="color:#0d0016;">有可能单个的catch不能完全处理一个异常，在进行一些校正处理以后，希望再交给更外层的调用<br> 链函数来处理，catch则可以通过重新抛出将异常传递给更上层的函数进行处理。</span></p> 
<pre><code class="language-cpp">double Division(int a, int b)
{
	// 当b == 0时抛出异常
	if (b == 0)
	{
		throw "Division by zero condition!";
	}
	return (double)a / (double)b;
}
void Func()
{
	// 这里可以看到如果发生除0错误抛出异常，另外下面的array没有得到释放。
	// 所以这里捕获异常后并不处理异常，异常还是交给外面处理，这里捕获了再
	// 重新抛出去。
	int* array = new int[10];
	try 
	{
		int len, time;
		cin &gt;&gt; len &gt;&gt; time;
		cout &lt;&lt; Division(len, time) &lt;&lt; endl;
	}
	catch (...)
	{
		cout &lt;&lt; "delete []" &lt;&lt; array &lt;&lt; endl;
		delete[] array;
		throw;
	}
	// ...
	cout &lt;&lt; "delete []" &lt;&lt; array &lt;&lt; endl;
	delete[] array;
}
int main()
{
	try
	{
		Func();
	}
	catch (const char* errmsg)
	{
		cout &lt;&lt; errmsg &lt;&lt; endl;
	}
	return 0;
}</code></pre> 
<p><span style="color:#0d0016;">运行截图：</span></p> 
<p><img alt="" height="83" src="https://images2.imgbox.com/f8/7b/fr8NH5Se_o.png" width="630"></p> 
<h3 id="3.3%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8%C2%A0"><span style="color:#0d0016;">3.3异常安全 </span></h3> 
<p><span style="color:#0d0016;">构造函数完成对象的构造和初始化，最好不要在构造函数中抛出异常，否则可能导致对象不<br> 完整或没有完全初始化<br> 析构函数主要完成资源的清理，最好不要在析构函数内抛出异常，否则可能导致资源泄漏(内<br> 存泄漏、句柄未关闭等)<br> C++中异常经常会导致资源泄漏的问题，比如在new和delete中抛出了异常，导致内存泄<br> 漏，在lock和unlock之间抛出了异常导致死锁，C++经常使用RAII来解决以上问题.</span></p> 
<h3 id="3.4%20%E5%BC%82%E5%B8%B8%E8%A7%84%E8%8C%83"><span style="color:#0d0016;">3.4 异常规范</span></h3> 
<p><span style="color:#0d0016;">1. 异常规格说明的目的是为了让函数使用者知道该函数可能抛出的异常有哪些。 可以在函数的<br> 后面接throw(类型)，列出这个函数可能抛掷的所有异常类型。<br> 2. 函数的后面接throw()，表示函数不抛异常。<br> 3. 若无异常接口声明，则此函数可以抛掷任何类型的异常。</span></p> 
<pre><code class="language-cpp">// 这里表示这个函数会抛出A/B/C/D中的某种类型的异常
void fun() throw(A，B，C，D);
// 这里表示这个函数只会抛出bad_alloc的异常
void* operator new (std::size_t size) throw (std::bad_alloc);
// 这里表示这个函数不会抛出异常
void* operator delete (std::size_t size, void* ptr) throw();
// C++11 中新增的noexcept，表示不会抛异常
thread() noexcept;
thread (thread&amp;&amp; x) noexcept;</code></pre> 
<h2 id="4.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB"><span style="color:#0d0016;">4.自定义异常体系</span></h2> 
<p><span style="color:#0d0016;">实际使用中很多公司都会自定义自己的异常体系进行规范的异常管理，因为一个项目中如果大家<br> 随意抛异常，那么外层的调用者基本就没办法玩了，所以实际中都会定义一套继承的规范体系。<br> 这样大家抛出的都是继承的派生类对象，捕获一个基类就可以了</span></p> 
<p><img alt="" height="528" src="https://images2.imgbox.com/ab/02/rEzQzTkI_o.png" width="1179"></p> 
<pre><code class="language-cpp">// 服务器开发中通常使用的异常继承体系
class Exception
{
public:
	Exception(const string&amp; errmsg, int id)
		:_errmsg(errmsg)
		, _id(id)
	{}
	virtual string what() const
	{
		return _errmsg;
	}
protected:
	string _errmsg;
	int _id;
};
class SqlException : public Exception
{
public:
	SqlException(const string&amp; errmsg, int id, const string&amp; sql)
		:Exception(errmsg, id)
		, _sql(sql)
	{}
	virtual string what() const
	{
		string str = "SqlException:";
		str += _errmsg;
		str += "-&gt;";
		str += _sql;
		return str;
	}
private:
	const string _sql;
};
class CacheException : public Exception
{
public:
	CacheException(const string&amp; errmsg, int id)
		:Exception(errmsg, id)
	{}
	virtual string what() const
	{
		string str = "CacheException:";
		str += _errmsg;
		return str;
	}
};
class HttpServerException : public Exception
{
public:
	HttpServerException(const string&amp; errmsg, int id, const string&amp; type)
		:Exception(errmsg, id)
		, _type(type)
	{}
	virtual string what() const
	{
		string str = "HttpServerException:";
		str += _type;
		str += ":";
		str += _errmsg;
		return str;
	}
private:
	const string _type;
};
void SQLMgr()
{
	srand(time(0));
	if (rand() % 7 == 0)
	{
		throw SqlException("权限不足", 100, "select * from name = '张三'");
	}
	//throw "xxxxxx";
}
void CacheMgr()
{
	srand(time(0));
	if (rand() % 5 == 0)
	{
		throw CacheException("权限不足", 100);
	}
	else if (rand() % 6 == 0)
	{
		throw CacheException("数据不存在", 101);
	}
	SQLMgr();
}
void HttpServer()
{
	// ...
	srand(time(0));
	if (rand() % 3 == 0)
	{
		throw HttpServerException("请求资源不存在", 100, "get");
	}
	else if (rand() % 4 == 0)
	{
		throw HttpServerException("权限不足", 101, "post");
	}
	CacheMgr();
}
int main()
{
	while (1)
	{
		try 
		{
			HttpServer();
		}
		catch (const Exception&amp; e) // 这里捕获父类对象就可以
		{
			// 多态
			cout &lt;&lt; e.what() &lt;&lt; endl;
			Sleep(1000);
		}
		catch (...)
		{
			cout &lt;&lt; "Unkown Exception" &lt;&lt; endl;
		}
	}
	return 0;
}</code></pre> 
<p><span style="color:#0d0016;">运行截图：</span></p> 
<p><img alt="" height="605" src="https://images2.imgbox.com/fb/b2/78PAETOT_o.png" width="1018"></p> 
<h2 id="5.C%2B%2B%E6%A0%87%E5%87%86%E5%BA%93%E7%9A%84%E5%BC%82%E5%B8%B8%E4%BD%93%E7%B3%BB%C2%A0"><span style="color:#0d0016;">5.C++标准库的异常体系 </span></h2> 
<p><span style="color:#0d0016;">C++ 提供了一系列标准的异常，定义在exception中，我们可以在程序中使用这些标准的异常。它们是以父子类层次结构组织起来的，如下所示：</span></p> 
<p><img alt="" height="601" src="https://images2.imgbox.com/4b/1d/GmlrYKVJ_o.png" width="714"></p> 
<p><img alt="" height="750" src="https://images2.imgbox.com/10/b9/EeIzC0g6_o.png" width="1051"><span style="color:#0d0016;">说明：实际中我们可以可以去继承exception类实现自己的异常类。但是实际中很多公司像上面一<br> 样自己定义一套异常继承体系。因为C++标准库设计的不够好用。 </span></p> 
<pre><code class="language-cpp">int main()
{
	try {
		vector&lt;int&gt; v(10, 5);
		// 这里如果系统内存不够也会抛异常
		v.reserve(1000000000);
		// 这里越界会抛异常
		v.at(10) = 100;
	}
	catch (const exception&amp; e) // 这里捕获父类对象就可以
	{
		cout &lt;&lt; e.what() &lt;&lt; endl;
	}
	catch (...)
	{
		cout &lt;&lt; "Unkown Exception" &lt;&lt; endl;
	}
	return 0;
}</code></pre> 
<h2 id="6.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BC%98%E7%BC%BA%E7%82%B9"><span style="color:#0d0016;">6.异常的优缺点</span></h2> 
<p><span style="color:#0d0016;"><strong>C++异常的优点：</strong></span><br><span style="color:#0d0016;">1. 异常对象定义好了，相比错误码的方式可以清晰准确的展示出错误的各种信息，甚至可以包<br> 含堆栈调用的信息，这样可以帮助更好的定位程序的bug。<br> 2. 返回错误码的传统方式有个很大的问题就是，在函数调用链中，深层的函数返回了错误，那<br> 么我们得层层返回错误，最外层才能拿到错误，具体看下面的详细解释。</span></p> 
<pre><code class="language-cpp">// 1.下面这段伪代码我们可以看到ConnnectSql中出错了，先返回给ServerStart，
ServerStart再返回给main函数，main函数再针对问题处理具体的错误。
// 2.如果是异常体系，不管是ConnnectSql还是ServerStart及调用函数出错，都不用检查，因
为抛出的异常异常会直接跳到main函数中catch捕获的地方，main函数直接处理错误。
 int ConnnectSql()
{
// 用户名密码错误
if (...)
return 1;
   // 权限不足
if (...)
return 2;
}
 int ServerStart() {
if (int ret = ConnnectSql() &lt; 0)
return ret;
   int fd = socket()
   if（fd &lt; 0）
     return errno;
}
 int main()
{
if(ServerStart()&lt;0)
...
return 0;
}</code></pre> 
<p><span style="color:#0d0016;">3. 很多的第三方库都包含异常，比如boost、gtest、gmock等等常用的库，那么我们使用它们<br> 也需要使用异常。<br> 4. 部分函数使用异常更好处理，比如构造函数没有返回值，不方便使用错误码方式处理。比如<br> T&amp; operator这样的函数，如果pos越界了只能使用异常或者终止程序处理，没办法通过返回值表示错误。</span></p> 
<p><span style="color:#0d0016;"><strong>C++异常的缺点：</strong><br> 1. 异常会导致程序的执行流乱跳，并且非常的混乱，并且是运行时出错抛异常就会乱跳。这会<br> 导致我们跟踪调试时以及分析程序时，比较困难。<br> 2. 异常会有一些性能的开销。当然在现代硬件速度很快的情况下，这个影响基本忽略不计。<br> 3. C++没有垃圾回收机制，资源需要自己管理。有了异常非常容易导致内存泄漏、死锁等异常<br> 安全问题。这个需要使用RAII来处理资源的管理问题。学习成本较高。<br> 4. C++标准库的异常体系定义得不好，导致大家各自定义各自的异常体系，非常的混乱。<br> 5. 异常尽量规范使用，否则后果不堪设想，随意抛异常，外层捕获的用户苦不堪言。所以异常<br> 规范有两点：一、抛出异常类型都继承自一个基类。二、函数是否抛异常、抛什么异常，都<br> 使用 func（）throw();的方式规范化。<br> 总结：异常总体而言，利大于弊，所以工程中我们还是鼓励使用异常的。另外其它的语言基本都是<br> 用异常处理错误，这也可以看出这是大势所趋。</span></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/0ddef3ac0a744de87ab64f109364aaf6/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">排序经典算法手撕代码</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/a7b94a2f808da3748da497f2cdca9d13/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">MongoDB实现批量更新语句</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>