<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>C&#43;&#43; 异常处理 - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="C&#43;&#43; 异常处理" />
<meta property="og:description" content="目录
一、异常的定义
二、异常的抛出和捕获
1.throw
2.try...catch
3.异常安全
4.异常规范
三、系统预定义异常
四、用户自定义异常
一、异常的定义 异常在C&#43;&#43;用于错误处理，C语言中一般使用返回值表示错误，C&#43;&#43;对错误处理进行了扩展，统一使用异常机制来处理程序中发生的错误。
C语言异常处理机制
①终止程序。缺陷：用户难以接受。如发生内存错误，除0错误时就会终止程序。
②返回错误码。缺陷：需要程序员自己去查找对应的错误。如系统的很多库的接口函数都是通过把错误码放到errno中，表示错误。
③C标准库中setjmp和longjmp组合
C&#43;&#43;的异常处理包括两个部分：抛出异常和捕获异常，如果抛出的异常被捕获，处理完之后程序会继续运行，如果抛出的异常未被捕获，将导致程序终止。
二、异常的抛出和捕获 异常是面向对象语言常用的一种处理错误的方式，当一个函数发现自己无法处理的错误时就可以抛出异常，让函数直接或间接的调用者处理这个错误。
throw：当程序出现问题时，可以通过throw关键字抛出一个异常。try：try块中放置的是可能抛出异常的代码，该代码块在执行时将进行异常错误检测，try块后面通常跟着一个或多个catch块。catch：如果try块中发生错误，则可以在catch块中定义对应要执行的代码块。 1.throw throw是用于抛出异常的关键字，用法如下：
throw 异常(对象);
在函数声明中应该指定可能抛出的异常，应该在函数声明指定。
void show(); //该函数可能抛出任何异常
void show()throw(); //该函数不抛出任何异常
void show()throw(char,int); //该函数可能抛出char和int型异常 2.try...catch 捕获异常使用try...catch关键字，用法如下：
try{ //可能抛出异常的代码 }catch(异常类型1 变量){//根据类型捕获异常 //处理异常类型1的代码 }catch(异常类型2 变量){//根据类型捕获异常 //处理异常类型2的代码 //throw 变量 ----- 继续向上一层抛出 }..... 异常被捕获后，执行对应的异常处理代码，然后继续执行try...catch之后的代码。若异常未被捕获，仍然导致程序终止。捕获异常后，如果当前无法处理，可以继续抛出。
异常的抛出和捕获的匹配原则：
①异常是通过抛出对象而引发的，该对象的类型决定了应该激活哪个catch的处理代码，如果抛出的异常对象没有捕获，或是没有匹配类型的捕获，那么程序会终止报错。
②被选中的处理代码（catch块）是调用链中与该对象类型匹配且离抛出异常位置最近的那一个
③抛出异常对象后，会生成一个异常对象的拷贝，因为抛出的异常对象可能是一个临时对象，所以会生成一个拷贝对象，这个拷贝的临时对象会在被catch以后销毁
④catch(...)可以捕获任意类型的异常，但捕获后无法知道异常错误是什么。
⑤实际异常的抛出和捕获的匹配原则有个例外，捕获和抛出的异常类型并不一定要完全匹配，可以抛出派生类对象，使用基类进行捕获，这个在实际中非常有用
在函数调用链中异常栈展开的匹配原则：
①当异常被抛出后，首先检查throw本身是否在try块内部，如果在则查找匹配的catch语句，如果有匹配的，则跳到catch的地方进行处理。
②如果当前函数栈没有匹配的catch则退出当前函数栈，继续在上一个调用函数栈中进行查找匹配的catch。找到匹配的catch子句并处理以后，会沿着catch子句后面继续执行，而不会跳回到原来抛异常的地方。
③如果到达main函数的栈，依旧没有找到匹配的catch，则终止程序。
void func1() { throw string(&#34;这是一个异常&#34;); } void func2() { func1(); } void func3() { func2(); } int main() { try { func3(); } catch (const string&amp; s) { cout &lt;&lt; &#34;" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/734de98f2f59984a94cc2d280233e275/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2022-10-10T15:04:21+08:00" />
<meta property="article:modified_time" content="2022-10-10T15:04:21+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">C&#43;&#43; 异常处理</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p></p> 
<p id="main-toc"><strong>目录</strong></p> 
<p id="%C2%A0%E4%B8%80%E3%80%81%E5%BC%82%E5%B8%B8%E7%9A%84%E5%AE%9A%E4%B9%89-toc" style="margin-left:0px;"><a href="#%C2%A0%E4%B8%80%E3%80%81%E5%BC%82%E5%B8%B8%E7%9A%84%E5%AE%9A%E4%B9%89" rel="nofollow"> 一、异常的定义</a></p> 
<p id="%E4%BA%8C%E3%80%81%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E6%8D%95%E8%8E%B7-toc" style="margin-left:0px;"><a href="#%E4%BA%8C%E3%80%81%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E6%8D%95%E8%8E%B7" rel="nofollow">二、异常的抛出和捕获</a></p> 
<p id="1.throw-toc" style="margin-left:40px;"><a href="#1.throw" rel="nofollow">1.throw</a></p> 
<p id="2.try...catch-toc" style="margin-left:40px;"><a href="#2.try...catch" rel="nofollow">2.try...catch</a></p> 
<p id="3.%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8-toc" style="margin-left:40px;"><a href="#3.%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8" rel="nofollow">3.异常安全</a></p> 
<p id="4.%E5%BC%82%E5%B8%B8%E8%A7%84%E8%8C%83-toc" style="margin-left:40px;"><a href="#4.%E5%BC%82%E5%B8%B8%E8%A7%84%E8%8C%83" rel="nofollow">4.异常规范</a></p> 
<p id="%E4%B8%89%E3%80%81%E7%B3%BB%E7%BB%9F%E9%A2%84%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8-toc" style="margin-left:0px;"><a href="#%E4%B8%89%E3%80%81%E7%B3%BB%E7%BB%9F%E9%A2%84%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8" rel="nofollow">三、系统预定义异常</a></p> 
<p id="%E5%9B%9B%E3%80%81%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8-toc" style="margin-left:0px;"><a href="#%E5%9B%9B%E3%80%81%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8" rel="nofollow">四、用户自定义异常</a></p> 
<hr id="hr-toc"> 
<p></p> 
<p><img alt="" src="https://images2.imgbox.com/d9/d7/JKWxsJBU_o.jpg"></p> 
<h2 id="%C2%A0%E4%B8%80%E3%80%81%E5%BC%82%E5%B8%B8%E7%9A%84%E5%AE%9A%E4%B9%89"> 一、异常的定义</h2> 
<p>异常在C++用于错误处理，C语言中一般使用返回值表示错误，C++对错误处理进行了扩展，统一使用异常机制来处理程序中发生的错误。</p> 
<p>C语言异常处理机制</p> 
<blockquote> 
 <p>①终止程序。缺陷：用户难以接受。如发生内存错误，除0错误时就会终止程序。</p> 
 <p></p> 
 <p>②返回错误码。缺陷：需要程序员自己去查找对应的错误。如系统的很多库的接口函数都是通过把错误码放到errno中，表示错误。</p> 
 <p></p> 
 <p>③C标准库中setjmp和longjmp组合</p> 
</blockquote> 
<p>C++的异常处理包括两个部分：<span style="color:#fe2c24;">抛出异常</span>和<span style="color:#fe2c24;">捕获异常</span>，如果抛出的异常被捕获，处理完之后程序会继续运行，如果抛出的异常未被捕获，将导致程序终止。</p> 
<h2 id="%E4%BA%8C%E3%80%81%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8A%9B%E5%87%BA%E5%92%8C%E6%8D%95%E8%8E%B7">二、异常的抛出和捕获</h2> 
<p>异常是面向对象语言常用的一种处理错误的方式，当一个函数发现自己无法处理的错误时就可以抛出异常，让函数直接或间接的调用者处理这个错误。</p> 
<blockquote> 
 <ul><li><span style="color:#fe2c24;">throw</span>：当程序出现问题时，可以通过throw关键字<span style="color:#fe2c24;">抛出一个异常</span>。</li><li><span style="color:#fe2c24;">try</span>：try块中放置的是<span style="color:#fe2c24;">可能抛出异常的代码，该代码块在执行时将进行异常错误检测</span>，<span style="background-color:#ffd900;">try块后面通常跟着一个或多个catch块</span>。</li><li><span style="color:#fe2c24;">catch</span>：<span style="color:#fe2c24;">如果try块中发生错误，则可以在catch块中定义对应要执行的代码块</span>。</li></ul> 
</blockquote> 
<h3 id="1.throw">1.throw</h3> 
<p>throw是用于抛出异常的关键字，用法如下：</p> 
<blockquote> 
 <p>throw 异常(对象);</p> 
</blockquote> 
<p>在函数声明中应该指定可能抛出的异常，应该在函数声明指定。</p> 
<blockquote> 
 <p>void show();                                //该函数<span style="background-color:#a2e043;">可能抛出任何异常</span></p> 
 <p>void show()throw();                     //该函数<span style="background-color:#38d8f0;">不抛出任何异常</span></p> 
 <p>void show()throw(char,int);         //该函数<span style="background-color:#4da8ee;">可能抛出char和int型异常</span>  </p> 
</blockquote> 
<h3 id="2.try...catch">2.try...catch</h3> 
<p>捕获异常使用try...catch关键字，用法如下：</p> 
<pre><code class="language-cpp">try{
    //可能抛出异常的代码    
}catch(异常类型1 变量){//根据类型捕获异常
    //处理异常类型1的代码
}catch(异常类型2 变量){//根据类型捕获异常
    //处理异常类型2的代码
    //throw 变量 ----- 继续向上一层抛出
}.....</code></pre> 
<p><span style="color:#fe2c24;">异常被捕获后，执行对应的异常处理代码</span>，然后继续执行<strong>try...catch<span style="color:#fe2c24;">之后的代码</span></strong>。若异常未被捕获，仍然导致程序终止。<strong>捕获异常后，如果当前无法处理，可以继续抛出</strong>。</p> 
<p>异常的抛出和捕获的匹配原则：</p> 
<blockquote> 
 <p>①异常是通过抛出对象而引发的，该对象的类型决定了应该激活哪个catch的处理代码，如果抛出的异常对象没有捕获，或是没有匹配类型的捕获，那么程序会终止报错。</p> 
 <p></p> 
 <p>②被选中的处理代码（catch块）是调用链中与该对象类型匹配且离抛出异常位置最近的那一个</p> 
 <p></p> 
 <p>③抛出异常对象后，会生成一个异常对象的拷贝，因为抛出的异常对象可能是一个临时对象，所以会生成一个拷贝对象，这个拷贝的临时对象会在被catch以后销毁</p> 
 <p></p> 
 <p>④<strong>catch(...)可以捕获任意类型的异常</strong>，但捕获后无法知道异常错误是什么。</p> 
 <p></p> 
 <p>⑤实际异常的抛出和捕获的匹配原则有个例外，捕获和抛出的异常类型并不一定要完全匹配，可以抛出派生类对象，使用基类进行捕获，这个在实际中非常有用<br>  </p> 
</blockquote> 
<p>在函数调用链中异常栈展开的匹配原则：</p> 
<blockquote> 
 <p>①当异常被抛出后，首先检查throw本身是否在try块内部，如果在则查找匹配的catch语句，如果有匹配的，则跳到catch的地方进行处理。</p> 
 <p></p> 
 <p>②如果当前函数栈没有匹配的catch则退出当前函数栈，继续在上一个调用函数栈中进行查找匹配的catch。<strong>找到匹配的catch子句并处理以后，会沿着catch子句后面继续执行，而不会跳回到原来抛异常的地方</strong>。</p> 
 <p></p> 
 <p>③如果到达main函数的栈，依旧没有找到匹配的catch，则终止程序。</p> 
</blockquote> 
<pre><code class="language-cpp">void func1()
{
	throw string("这是一个异常");
}
void func2()
{
	func1();
}
void func3()
{
	func2();
}
int main()
{
	try
	{
		func3();
	}
	catch (const string&amp; s)
	{
		cout &lt;&lt; "错误描述：" &lt;&lt; s &lt;&lt; endl;
	}
	catch (...)
	{
		cout &lt;&lt; "未知异常" &lt;&lt; endl;
	}
	return 0;
}
</code></pre> 
<p>当func1中的异常被抛出后：</p> 
<p>1.首先会检查throw本身是否在try块内部，这里由于<strong>throw不在try块内部</strong>，因此会退出func3所在的函数栈，继续在上一个调用函数栈中进行查找，即func2所在的函数栈。</p> 
<p>2.由于func2中也没有匹配的catch，因此会继续在上一个调用函数栈中进行查找，即func3所在的函数栈。</p> 
<p>3.func3中也没有匹配的catch，于是就会在<strong>main所在的函数栈中进行查找</strong>，最终在main函数栈中找到了匹配的catch。</p> 
<p>4.这时就会<strong>跳到main函数中对应的catch块中执行对应的代码块，执行完后继续执行该代码块后续的代码</strong>。</p> 
<h3 id="3.%E5%BC%82%E5%B8%B8%E5%AE%89%E5%85%A8">3.异常安全</h3> 
<p>将抛异常导致的安全问题叫做异常安全问题，对于异常安全问题下面给出几点建议：</p> 
<blockquote> 
 <p>①构造函数完成对象的构造和初始化，<strong>最好不要在构造函数中抛出异常，否则可能导致对象不完整或没有完全初始化</strong>。</p> 
 <p></p> 
 <p>②析构函数主要完成对象资源的清理，<strong>最好不要在析构函数中抛出异常，否则可能导致资源泄露（内存泄露、句柄未关闭等</strong>）。</p> 
 <p></p> 
 <p>③C++中异常经常会导致<strong>资源泄露</strong>的问题，比如在new和delete中抛出异常，导致内存泄露，在lock和unlock之间抛出异常导致死锁，C++经常使用RAII的方式来解决以上问题。<br>  </p> 
</blockquote> 
<h3 id="4.%E5%BC%82%E5%B8%B8%E8%A7%84%E8%8C%83">4.异常规范</h3> 
<p>为了让函数使用者知道某个函数可能抛出哪些类型的异常，C++标准规定</p> 
<blockquote> 
 <p>①在函数的后面接<strong><span style="color:#ed7976;"><code>throw(type1, type2, ...)</code></span></strong>，<strong>列出这个函数可能抛掷的所有异常类型</strong>。</p> 
 <p></p> 
 <p>②在函数的后面接<span style="color:#fe2c24;"><code>throw()</code>或<code>noexcept</code>（C++11）</span>，<strong>表示该函数不抛异常</strong>。</p> 
 <p></p> 
 <p>③<span style="color:#fe2c24;">若无异常接口声明，则此函数可以抛掷任何类型的异常</span>。（异常接口声明不是强制的）</p> 
</blockquote> 
<pre><code class="language-cpp">//表示func函数可能会抛出A/B/C/D类型的异常
void func() throw(A, B, C, D);
//表示这个函数只会抛出bad_alloc的异常
void* operator new(std::size_t size) throw(std::bad_alloc);
//表示这个函数不会抛出异常
void* operator new(std::size_t size, void* ptr) throw();
</code></pre> 
<h2 id="%E4%B8%89%E3%80%81%E7%B3%BB%E7%BB%9F%E9%A2%84%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8">三、系统预定义异常</h2> 
<p>C++标准库当中的异常也是一个基础体系，其中exception就是各个异常类的基类，我们可以在程序中使用这些标准的异常，它们之间的继承关系如下：</p> 
<p><img alt="" height="748" src="https://images2.imgbox.com/3e/96/7I2nA3ou_o.png" width="1076"></p> 
<p> </p> 
<blockquote> 
 <p>std::exception    该异常是所有标准C++异常的父类。<br> std::bad_alloc    该异常可以通过new抛出。<br> std::bad_cast    该异常可以通过dynamic_cast抛出。<br> std::bad_exception    这在处理C++程序中无法预期的异常时非常有用。<br> std::bad_typeid    该异常可以通过typeid抛出。<br> std::logic_error    理论上可以通过读取代码来检测到的异常。<br> std::domain_error    当使用了一个无效的数学域时，会抛出该异常。<br> std::invalid_argument    当使用了无效的参数时，会抛出该异常。<br> std::length_error    当创建了太长的std::string时，会抛出该异常。<br> std::out_of_range    该异常可以通过方法抛出，例如std::vector和std::bitset&lt;&gt;::operator。<br> std::runtime_error    理论上不可以通过读取代码来检测到的异常。<br> std::overflow_error    当发生数学上溢时，会抛出该异常。<br> std::range_error    当尝试存储超出范围的值时，会抛出该异常。<br> std::underflow_error    当发生数学下溢时，会抛出该异常。</p> 
</blockquote> 
<h2 id="%E5%9B%9B%E3%80%81%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8">四、用户自定义异常</h2> 
<p>在C++项目开发中，详细设计时应该设计好异常的框架，通常的做法就是<strong>定义一个异常的基类，项目中所有的异常都是该类的子类/间接子类</strong>。</p> 
<p>最基础的异常类至少需要包含错误编号和错误描述两个成员变量，甚至还可以包含当前函数栈帧的调用链等信息。该异常类中一般还会提供两个成员函数，分别用来获取错误编号和错误描述。</p> 
<pre><code class="language-cpp">class Exception
{
public:
	Exception(int errid, const char* errmsg)
		:_errid(errid)
		, _errmsg(errmsg)
	{}
	int GetErrid() const
	{
		return _errid;
	}
	virtual string what() const
	{
		return _errmsg;
	}
protected:
	int _errid;     //错误编号
	string _errmsg; //错误描述
	//...
};


class CacheException : public Exception
{
public:
	CacheException(int errid, const char* errmsg)
		:Exception(errid, errmsg)
	{}
	virtual string what() const  //重写
	{
		string msg = "CacheException: ";
		msg += _errmsg;
		return msg;
	}
protected:
	//...
};
</code></pre> 
<p>其他模块如果要对这个异常类进行扩展，<strong>必须继承这个基础的异常类</strong>，可以在继承后的异常类中按需添加某些成员变量，或是对继承下来的<span style="color:#fe2c24;"><strong>虚函数what进行重写</strong></span>，使其能告知程序员更多的异常信息。</p> 
<p><span style="color:#fe2c24;">异常类的成员变量不能设置为私有，因为私有成员在子类中是不可见的</span>。<strong><span style="color:#fe2c24;">基类Exception中的what成员函数最好定义为虚函数，方便子类对其进行重写，从而达到多态的效果</span></strong>。</p> 
<p> </p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/a658c77164a7351b63a1b08db5c8f933/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">[转]运放电流检测采样电路电压采样电路</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/89d4bc7b2ccfdff910d56bdae436974c/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">MR-GMMapping:基于高斯混合模型的通信高效多机器人映射系统</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>