<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Java throws 使用 - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Java throws 使用" />
<meta property="og:description" content="在开发中，如果去调用别人写的方法时，是否能知道别人写的方法是否会发生异常？这是很难判断的。针对这种情况，Java总允许在方法的后面使用throws关键字对外声明该方法有可能发生异常，这样调用者在调用方法时，就明确地知道该方法有异常，并且必须在程序中对异常进行处理，否则编译无法通过。
如下面代码
package www.kangxg.jdbc; public class Example { public static void main(String[] args) { // TODO Auto-generated method stub int result = divide(4,2); System.out.println(result); } public static int divide(int x,int y) throws Exception { int result = x/y; return result; } } 这时候 编译器上会有错误提示 Unhandled exception type Exception 所以需要对调用divide()方法进行try...catch处理 package www.kangxg.jdbc; public class Example { public static void main(String[] args) { try { int result = divide(4,2); System.out.println(result); } catch (Exception e) { e." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/1184b7eabf39cf24d1185086ddfc6c22/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2018-01-26T23:12:11+08:00" />
<meta property="article:modified_time" content="2018-01-26T23:12:11+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Java throws 使用</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>在开发中，如果去调用别人写的方法时，是否能知道别人写的方法是否会发生异常？这是很难判断的。针对这种情况，Java总允许在方法的后面使用throws关键字对外声明该方法有可能发生异常，这样调用者在调用方法时，就明确地知道该方法有异常，并且必须在程序中对异常进行处理，否则编译无法通过。</p> 
<p>如下面代码</p> 
<p><br> </p> 
<p></p> 
<pre class="hljs gams" style="overflow:auto; font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:13px; padding:15px; margin-top:0px; margin-bottom:20px; line-height:1.42857; color:rgb(101,123,131); background:rgb(246,246,246); border:1px solid rgb(204,204,204)"><code class="gams" style="font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:12px; background-color:transparent; padding:0px; border:none">package www.kangxg.jdbc;

public class Example {

    public static void main(String[] args) {
        // TODO Auto-generated method stub
       int result = divide(4,2);
       System.out.println(result);
    }
    
    public static int divide(int x,int y) throws Exception
    {
        int result = x/y;
        return result;
    }

}
</code></pre> 这时候 编译器上会有错误提示  Unhandled exception type Exception 
<p>所以需要对调用divide()方法进行try...catch处理 <br> </p> 
<p><br> </p> 
<p></p> 
<pre class="hljs gams" style="overflow:auto; font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:13px; padding:15px; margin-top:0px; margin-bottom:20px; line-height:1.42857; color:rgb(101,123,131); background:rgb(246,246,246); border:1px solid rgb(204,204,204)"><code class="gams" style="font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:12px; background-color:transparent; padding:0px; border:none">package www.kangxg.jdbc;

public class Example {

    public static void main(String[] args) {
        
      try {
         int    result = divide(4,2);
          System.out.println(result);
       } catch (Exception e) {
        
          e.printStackTrace();
       }
      
    }
    
    public static int divide(int x,int y) throws Exception
    {
        int result = x/y;
        return result;
    }

}</code></pre> 
<p>debug 运行程序</p> 
<p><img src="https://images2.imgbox.com/1c/af/XOiKBCQR_o.png" alt=""></p> 
<p>当 调用divide()方法时，如果不知道如何处理声明抛出的异常，也可以使用throws 关键字继续抛异常，这样程序也能编译运行。但是注意的是，程序一旦发生异常，如果没有被处理，程序就会非正常终止。如下：</p> 
<p></p> 
<pre class="hljs gams" style="overflow:auto; font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:13px; padding:15px; margin-top:0px; margin-bottom:20px; line-height:1.42857; color:rgb(101,123,131); background:rgb(246,246,246); border:1px solid rgb(204,204,204)"><code class="gams" style="font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:12px; background-color:transparent; padding:0px; border:none">package www.kangxg.jdbc;

public class Example {

    public static void main(String[] args) throws Exception {
        
          int    result = divide(4,0);
          System.out.println(result);
      
    }
    
    public static int divide(int x,int y) throws Exception
    {
        int result = x/y;
        return result;
    }

}</code></pre> 
<p>   <br> </p> 
<p>debug运行程序</p> 
<p> </p> 
<p>  <img src="https://images2.imgbox.com/f8/73/uIcbyhfd_o.png" alt=""></p> 
<p><br> </p> 
<p><br> </p> 
<p>Java 运行时异常与编译时异常</p> 
<p>1. 编译时异常</p> 
<p>   在Java 中，Exception类中除了RuntimeException 类及其子类外都是编译时异常。编译时异常的特点是Java编译器会对其进行检查，如果出现异常就必须对异常进行处理，否则程序无法编译通过。</p> 
<p>  处理方法</p> 
<p>   使用try... catch 语句对异常进行捕获</p> 
<p>   使用throws 关键字声明抛出异常，调用者对其进行处理</p> 
<p>2.运行时异常</p> 
<p>  RuntimeException 类及其子类运行异常。运行时异常的特点是Java编译器不会对其进行检查。也就是说，当程序中出现这类异常时，即使没有使用try... catch 语句捕获使用throws关键字声明抛出。程序也能编译通过。运行时异常一般是程序中的逻辑错误引起的，在程序运行时无法修复。例如 数据取值越界。</p> 
<p>三 自定义异常</p> 
<p>  JDK中定义了大量的异常类，虽然这些异常类可以描述编程时出现的大部分异常情况，但是在程序开发中有时可能需要描述程序中特有的异常情况。例如divide()方法中不允许被除数为负数。为类解决这个问题，在Java中允许用户自定义异常，但自定义的异常类必须继承自Exception或其子类。例子如下</p> 
<p><br> </p> 
<p></p> 
<pre class="hljs gams" style="overflow:auto; font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:13px; padding:15px; margin-top:0px; margin-bottom:20px; line-height:1.42857; color:rgb(101,123,131); background:rgb(246,246,246); border:1px solid rgb(204,204,204)"><code class="gams" style="font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:12px; background-color:transparent; padding:0px; border:none">package www.kangxg.jdbc;

public class DivideDivideByMinusException  extends Exception {
    
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    public DivideDivideByMinusException(){
        super();
    }
    
    public DivideDivideByMinusException(String message)
    {
        super(message);
    }
}
</code></pre> 
<p>  </p> 
<pre class="hljs gams" style="overflow:auto; font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:13px; padding:15px; margin-top:0px; margin-bottom:20px; line-height:1.42857; color:rgb(101,123,131); background:rgb(246,246,246); border:1px solid rgb(204,204,204)"><code class="gams" style="font-family:Menlo,Monaco,Consolas,'Courier New',monospace; font-size:12px; background-color:transparent; padding:0px; border:none">package www.kangxg.jdbc;

public class Example {

    public static void main(String[] args) throws Exception {
        
        try {
             int    result = divide(4,-2);
              System.out.println(result);
         } catch (DivideDivideByMinusException e) {
            
             System.out.println(e.getMessage());
         }
      
    }
    
    public static int divide(int x,int y) throws DivideDivideByMinusException
    {
        if(y&lt;0)
        {
            throw new DivideDivideByMinusException("被除数是负数");
        }
        int result = x/y;
        return result;
    }

}</code></pre> 
<p>   <br> </p> 
<p>Debug 运行</p> 
<p><br> </p> 
<p>  <img src="https://images2.imgbox.com/f2/c5/bdJEUzvy_o.png" alt=""></p> 
<p><br> </p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/0364038f09f4fbdf25029ddc2e9d64f5/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/14fc5b10f1dd56b53bc74c2a76d1fc7b/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">错误	MSB3644	未找到框架“.NETFramework,Version=v4.6.2”的引用程序集 的解决方法</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>