<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>C&#43;&#43;异常处理之terminate函数 - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="C&#43;&#43;异常处理之terminate函数" />
<meta property="og:description" content="C&#43;&#43;中处理异常的过程是这样的：在执行程序发生异常，可以不在本函数中处理，而是抛出一个错误信息，把它传递给上一级的函数来解决，上一级解决不了，再传给其上一级，由其上一级处理。如此逐级上传，直到最高一级还无法处理的话，运行系统会自动调用系统函数terminate，
学会使用terminate函数有助于异常处理 一 当一个异常产生的时候调用terminate函数，代码：
#include &lt;iostream&gt; #include &lt;exception&gt; using namespace std; void on_terminate(){ cout&lt;&lt;&#34;terninate function called!&#34;&lt;&lt;endl; cin.get(); } int main(void){ set_terminate(on_terminate); throw exception(); cout&lt;&lt;&#34;terminate function not called!&#34;&lt;&lt;endl; cin.get(); return 0; } terminate 被调用的情况：
1 当发送一个异常，并且构造函数产生异常
2 当发送一个异常，或者析构函数产生异常
3 一个静态对象的构造或者析构发送一个异常
4 以atexit注册的函数发生异常的时候
5 自定义一个异常，但是实际上没有异常产生的时候
6 调用缺省的unexcepted()函数时候
例子说话：
#include &lt;iostream&gt; #include &lt;exception&gt; using namespace std; void on_terminate(){ cout&lt;&lt;&#34;terminate function called!&#34;&lt;&lt;endl; cin.get(); } class custom_exception{ custom_exception(){ } custom_exception(const custom_exception&amp; excep){ throw exception(); } }; void case_1(){ try{ throw custom_exception(); } catch(." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/0fea97902d39a4da0dfd30251d7ad3e2/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2013-08-21T09:44:49+08:00" />
<meta property="article:modified_time" content="2013-08-21T09:44:49+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">C&#43;&#43;异常处理之terminate函数</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p><span style="color:#393939">C++</span><span style="color:#393939">中处理异常的过程是这样的：在执行程序发生异常，可以不在本函数中处理，而是抛出一个错误信息，把它传递给上一级的函数来解决，上一级解决不了，再传给其上一级，由其上一级处理。如此逐级上传，直到最高一级还无法处理的话，运行系统会自动调用系统函数</span><span style="color:#393939">terminate</span><span style="color:#393939">，</span></p> 学会使用terminate函数有助于异常处理 
<br> 
<p>一 当一个异常产生的时候调用terminate函数，代码：</p> 
<p></p> 
<pre><code class="language-cpp">#include &lt;iostream&gt;
#include &lt;exception&gt;
using namespace std;
void on_terminate(){
 cout&lt;&lt;"terninate function called!"&lt;&lt;endl;
 cin.get();
}
int main(void){
 set_terminate(on_terminate);
 throw exception();
 cout&lt;&lt;"terminate function not called!"&lt;&lt;endl;
 cin.get();
 return 0;
}
</code></pre> 
<span lang="EN-US" style="font-size:9.5pt; font-family:微软雅黑">terminate</span> 
<span style="font-size:9.5pt; font-family:微软雅黑">被调用的情况：<span lang="EN-US"><br> 1 </span>当发送一个异常，并且构造函数产生异常<span lang="EN-US"><br> 2 </span>当发送一个异常，或者析构函数产生异常<span lang="EN-US"><br> 3 </span>一个静态对象的构造或者析构发送一个异常<span lang="EN-US"><br> 4 </span>以<span lang="EN-US">atexit</span>注册的函数发生异常的时候<span lang="EN-US"><br> 5 </span>自定义一个异常，但是实际上没有异常产生的时候<span lang="EN-US"><br> 6 </span>调用缺省的<span lang="EN-US">unexcepted()</span>函数时候<span lang="EN-US"><br> </span>例子说话：<span lang="EN-US"><br> <br> </span></span> 
<pre><code class="language-cpp">#include &lt;iostream&gt;
#include &lt;exception&gt;
using namespace std;
void on_terminate(){
 cout&lt;&lt;"terminate function called!"&lt;&lt;endl;
 cin.get();
}
class custom_exception{
 custom_exception(){
 }
 custom_exception(const custom_exception&amp; excep){
  throw exception();
 }
};
void case_1(){
 try{
  throw custom_exception();
 }
 catch(...){
 }
}
</code></pre> 
<br> 
<span style="font-size:9.5pt; font-family:微软雅黑">当一个函数抛出了一个<span lang="EN-US">throw</span>异常的时候，如果该函数内部构造了对象的话，系统会先对该对象调用析构函数，当对象调用完了析构函数以后，才开始执行异常的抛出工作。<span lang="EN-US"><br> </span>同时在具有继承关系的类的异常中，子类的异常应该放在前面，而基类的异常应该放到最后面，这样可以使子类的异常先获得处理，父类的异常最后处理。<span lang="EN-US"><br> <br> </span></span> 
<pre><code class="language-cpp">#include&lt;iostream&gt; 
using namespace std; 
class X 
{ 
public: 
 class Trouble {};   //注意：类中嵌套类的申明和定义，学习!!! 
  class small: public Trouble {}; 
  class big:public Trouble {};//类中的继承!!! 
  void f(){ 
  throw big(); 
 } 
}; 
int main() 
{ 
  X x; 
  try{ 
    x.f(); 
  } 
  catch(X::Trouble &amp;) 
  { 
    cout&lt;&lt;"caught Trouble"&lt;&lt;endl; 
  } 
  catch(X::small&amp;) 
  { 
    cout&lt;&lt;"caught small"&lt;&lt;endl;
 } 
  catch(X::big&amp;) 
  { 
    cout&lt;&lt;"caught big"&lt;&lt;endl; 
  } 
   return 0; 
} 
</code></pre> 
<p></p> 
<p style="margin:0cm; margin-bottom:.0001pt; line-height:19.0pt"><span style="font-size:9.5pt; font-family:微软雅黑">如果这样的话，抛出的<span lang="EN-US">big()</span>类型异常则被<span lang="EN-US">trouble</span>类垄断，应该倒着写才可以实现顺序捕获所有异常，另外使用<span lang="EN-US">...</span>可以捕捉所有的异常，这个应该放到最后面才可以。<span lang="EN-US"><br> </span>省略号异常处理器不允许接受任何参数，所以无法得到任何相关异常的信息，也无法知道异常的类型，这种<span lang="EN-US">catch</span>语句经常用于清理资源并重新抛出所捕获的异常。<span lang="EN-US"></span></span></p> 
<br> 
<br> 
<br>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/3e87ad4e3aeee3175ce505d35fcc39f0/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Spring英文参考文档翻译</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/788874d5ad96a4328197031e6319a377/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">oracle err 959,oracle 错误 959 处理办法</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>